[2025-09-06T16:37:18.712+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T16:37:18.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.show_filepath manual__2025-09-06T16:37:18.166247+00:00 [queued]>
[2025-09-06T16:37:18.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.show_filepath manual__2025-09-06T16:37:18.166247+00:00 [queued]>
[2025-09-06T16:37:18.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T16:37:18.762+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): show_filepath> on 2025-09-06 16:37:18.166247+00:00
[2025-09-06T16:37:18.771+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T16:37:18.773+0000] {standard_task_runner.py:64} INFO - Started process 4206 to run task
[2025-09-06T16:37:18.773+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'show_filepath', 'manual__2025-09-06T16:37:18.166247+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmppvvb3fxg']
[2025-09-06T16:37:18.776+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask show_filepath
[2025-09-06T16:37:18.821+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.show_filepath manual__2025-09-06T16:37:18.166247+00:00 [running]> on host dd8e0e853e24
[2025-09-06T16:37:18.883+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='show_filepath' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T16:37:18.166247+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T16:37:18.166247+00:00'
[2025-09-06T16:37:18.884+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T16:37:18.886+0000] {logging_mixin.py:188} INFO - ðŸ‘€ Looking for file at: /opt/***/data/customer_churn_data.csv
[2025-09-06T16:37:18.889+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/customer_churn_data.csv
[2025-09-06T16:37:18.889+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T16:37:18.905+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=load_customers_to_postgres, task_id=show_filepath, run_id=manual__2025-09-06T16:37:18.166247+00:00, execution_date=20250906T163718, start_date=20250906T163718, end_date=20250906T163718
[2025-09-06T16:37:18.917+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-06T16:37:18.937+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-06T16:37:18.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
