[2025-09-06T06:59:30.747+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T06:59:30.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.create_bronze_schema_and_table manual__2025-09-06T06:54:27.961614+00:00 [queued]>
[2025-09-06T06:59:30.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.create_bronze_schema_and_table manual__2025-09-06T06:54:27.961614+00:00 [queued]>
[2025-09-06T06:59:30.776+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-06T06:59:30.782+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_bronze_schema_and_table> on 2025-09-06 06:54:27.961614+00:00
[2025-09-06T06:59:30.786+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'create_bronze_schema_and_table', 'manual__2025-09-06T06:54:27.961614+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmpmzwwusip']
[2025-09-06T06:59:30.789+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask create_bronze_schema_and_table
[2025-09-06T06:59:30.788+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1517) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T06:59:30.790+0000] {standard_task_runner.py:64} INFO - Started process 1518 to run task
[2025-09-06T06:59:30.818+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.create_bronze_schema_and_table manual__2025-09-06T06:54:27.961614+00:00 [running]> on host 9f9bb90816fe
[2025-09-06T06:59:30.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='create_bronze_schema_and_table' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T06:54:27.961614+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T06:54:27.961614+00:00'
[2025-09-06T06:59:30.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T06:59:30.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T06:59:30.877+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_customers_to_postgres.py", line 75, in create_bronze_schema_and_table
    with pg.get_conn() as conn:
         ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-09-06T06:59:30.881+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_customers_to_postgres, task_id=create_bronze_schema_and_table, run_id=manual__2025-09-06T06:54:27.961614+00:00, execution_date=20250906T065427, start_date=20250906T065930, end_date=20250906T065930
[2025-09-06T06:59:30.886+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task create_bronze_schema_and_table (The conn_id `postgres_default` isn't defined; 1518)
[2025-09-06T06:59:30.892+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T06:59:30.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T06:59:30.907+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
