[2025-09-06T14:15:07.096+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T14:15:07.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transformations.dbt_test manual__2025-09-06T14:14:55.024861+00:00 [queued]>
[2025-09-06T14:15:07.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transformations.dbt_test manual__2025-09-06T14:14:55.024861+00:00 [queued]>
[2025-09-06T14:15:07.119+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-06T14:15:07.124+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2025-09-06 14:14:55.024861+00:00
[2025-09-06T14:15:07.129+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_transformations', 'dbt_test', 'manual__2025-09-06T14:14:55.024861+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dbt_transformations.py', '--cfg-path', '/tmp/tmpkod20l5p']
[2025-09-06T14:15:07.131+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask dbt_test
[2025-09-06T14:15:07.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T14:15:07.132+0000] {standard_task_runner.py:64} INFO - Started process 1179 to run task
[2025-09-06T14:15:07.153+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_transformations.dbt_test manual__2025-09-06T14:14:55.024861+00:00 [running]> on host dd8e0e853e24
[2025-09-06T14:15:07.192+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T14:14:55.024861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T14:14:55.024861+00:00'
[2025-09-06T14:15:07.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T14:15:07.200+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-06T14:15:07.200+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PATH="$PATH:/home/***/.local/bin" && cd /opt/***/dbt && DBT_PROFILES_DIR="/opt/***/dbt" dbt test --project-dir . --profiles-dir "/opt/***/dbt"']
[2025-09-06T14:15:07.205+0000] {subprocess.py:86} INFO - Output:
[2025-09-06T14:15:08.449+0000] {subprocess.py:93} INFO - [0m14:15:08  Running with dbt=1.10.11
[2025-09-06T14:15:08.575+0000] {subprocess.py:93} INFO - [0m14:15:08  Registered adapter: postgres=1.8.2
[2025-09-06T14:15:08.802+0000] {subprocess.py:93} INFO - [0m14:15:08  Found 3 models, 1 source, 550 macros
[2025-09-06T14:15:08.804+0000] {subprocess.py:93} INFO - [0m14:15:08  Nothing to do. Try checking your model configs and model specification args
[2025-09-06T14:15:10.694+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-06T14:15:10.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T14:15:10.707+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_transformations, task_id=dbt_test, run_id=manual__2025-09-06T14:14:55.024861+00:00, execution_date=20250906T141455, start_date=20250906T141507, end_date=20250906T141510
[2025-09-06T14:15:10.758+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-06T14:15:10.767+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T14:15:10.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
